<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="5.9.0" />
    <PackageReference Include="PossumLabs.Specflow.Core" Version="1.0.0-CI00026" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
  </ItemGroup>

</Project>
